# Container-based builds used if "sudo: false" --> fast boot (1-6s)
# https://docs.travis-ci.com/user/ci-environment/
sudo: false

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

env:
  matrix:
    - DJANGO="1.8"
    - DJANGO="1.9"

install:
  - pip install -U tox coveralls

script:
  - tox -vvvv -e $( echo $TRAVIS_PYTHON_VERSION | sed -e 's/^2\./py2/' -e 's/^3\./py3/' )-django${DJANGO}

after_success:
  coveralls
